/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.gr03.view;

/**
 *
 * @author Drouet
 */
public class MovimientosFrm extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrm
     */
    public MovimientosFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        btnVerMovimientos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMovimientos = new javax.swing.JMenu();
        menuRetiro = new javax.swing.JMenu();
        menuDeposito = new javax.swing.JMenu();
        menuTransferencia = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 233, 238));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 16, 16));
        jLabel1.setText("Movimientos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 16, 16));
        jLabel2.setText("EurekaBank");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/gr03/img/logo.jpeg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 16, 16));
        jLabel3.setText("Cuenta:");

        txtCuenta.setBackground(new java.awt.Color(255, 255, 255));
        txtCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCuenta.setForeground(new java.awt.Color(16, 16, 16));

        btnVerMovimientos.setBackground(new java.awt.Color(51, 153, 255));
        btnVerMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        btnVerMovimientos.setText("Ver moviminetos");
        btnVerMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMovimientosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnVerMovimientos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerMovimientos))
            .addComponent(jLabel4)
        );

        menuMovimientos.setText("Movimientos");
        menuMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMovimientosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuMovimientos);

        menuRetiro.setText("Retiro");
        menuRetiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRetiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRetiroMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRetiro);

        menuDeposito.setText("Deposito");
        menuDeposito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDepositoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDeposito);

        menuTransferencia.setText("Transferencia");
        menuTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTransferenciaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuTransferencia);

        jMenu1.setText("Cerrar Sesión");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMovimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMovimientosMouseClicked

    }//GEN-LAST:event_menuMovimientosMouseClicked

    private void menuRetiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRetiroMouseClicked
        RetiroFrm retiroFrm = new RetiroFrm();
        retiroFrm.setVisible(true);
        this.dispose(); // Opcional
    }//GEN-LAST:event_menuRetiroMouseClicked

    private void menuDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDepositoMouseClicked
        DepositoFrm depositoFrm = new DepositoFrm();
        depositoFrm.setVisible(true);
        this.dispose(); // Opcional
    }//GEN-LAST:event_menuDepositoMouseClicked

    private void menuTransferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransferenciaMouseClicked
        TransferenciasFrm transFrm = new TransferenciasFrm();
        transFrm.setVisible(true);
        this.dispose(); // Opcional
    }//GEN-LAST:event_menuTransferenciaMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        LoginFrm transFrm = new LoginFrm();
        transFrm.setVisible(true);
        this.dispose(); // Opcional
    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnVerMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMovimientosActionPerformed
        // Obtener los datos del formulario
        String numeroCuenta = txtCuenta.getText();
        MovimientosTablaFrm movimientosFrm = new MovimientosTablaFrm(numeroCuenta);
        movimientosFrm.setVisible(true);
    }//GEN-LAST:event_btnVerMovimientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimientosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimientosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimientosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimientosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimientosFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerMovimientos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuDeposito;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuRetiro;
    private javax.swing.JMenu menuTransferencia;
    private javax.swing.JTextField txtCuenta;
    // End of variables declaration//GEN-END:variables
}
